modLoader="javafml"
license="MIT"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/Polar-28/oxygenalertmod"

[[mods]]
    modId="oxygenalertmod"
    version="0.0.2"
    displayName="Oxygen Alert Mod"
    logoFile=""
    credits="Thanks to forge fml mcp Mojang"
    authors="Polar"
    description="A mod for playing an audio when the oxygen of the player is low."

[[dependencies.oxygenalertmod]]
    modId="forge" 
    mandatory=true 
    versionRange="[47.1,)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.oxygenalertmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"